# Generated by Django 3.0.2 on 2020-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Branche', models.CharField(max_length=100)),
                ('Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Number', models.IntegerField()),
                ('Professor', models.CharField(max_length=100)),
                ('TotalMarks', models.IntegerField()),
                ('ExpectedMarks', models.IntegerField()),
            ],
        ),
    ]
