# Generated by Django 3.0.2 on 2020-02-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200206_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='College',
        ),
    ]
