# Generated by Django 3.0.2 on 2020-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_remove_students_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='College',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
