# Generated by Django 3.0.2 on 2020-02-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
